# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lock_type', models.CharField(choices=[('AVAILABILITY', 'Availability Check'), ('BOOKING', 'Booking Creation'), ('PAYMENT', 'Payment Processing'), ('CANCELLATION', 'Cancellation'), ('COMPLETION', 'Completion')], max_length=20)),
                ('resource_type', models.CharField(help_text="e.g., 'asset', 'booking'", max_length=50)),
                ('resource_id', models.UUIDField()),
                ('owner_id', models.UUIDField()),
                ('owner_process', models.CharField(help_text='Process ID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Booking Lock',
                'verbose_name_plural': 'Booking Locks',
                'db_table': 'booking_locks',
            },
        ),
        migrations.CreateModel(
            name='BookingStatusTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], max_length=20)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('ADMIN', 'Admin'), ('CELERY', 'Celery Task')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True, help_text='Required for admin overrides')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Status Transition',
                'verbose_name_plural': 'Booking Status Transitions',
                'db_table': 'booking_status_transitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingTimeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Booking Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('CONTRACT_GENERATED', 'Contract Generated'), ('CONTRACT_ACCEPTED', 'Contract Accepted'), ('CONFIRMED', 'Booking Confirmed'), ('REMINDER_SENT', 'Reminder Sent'), ('STARTED', 'Booking Started'), ('EXTENDED', 'Booking Extended'), ('COMPLETED', 'Booking Completed'), ('CANCELLED', 'Booking Cancelled'), ('LATE_DETECTED', 'Late Return Detected'), ('LATE_FEE_CHARGED', 'Late Fee Charged'), ('DISPUTE_RAISED', 'Dispute Raised'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('NO_SHOW', 'No Show'), ('EXPIRED', 'Booking Expired'), ('PAYMENT_REFUNDED', 'Payment Refunded')], max_length=30)),
                ('description', models.TextField()),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('ADMIN', 'Admin'), ('CELERY', 'Celery Task')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Timeline',
                'verbose_name_plural': 'Booking Timeline Events',
                'db_table': 'booking_timeline',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('booked_quantity', models.PositiveIntegerField(default=0)),
                ('cache_version', models.PositiveIntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Availability Slot',
                'verbose_name_plural': 'Availability Slots',
                'db_table': 'availability_slots',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_breakdown', models.JSONField(blank=True, default=dict)),
                ('grace_period_minutes', models.PositiveIntegerField(default=15, help_text='Grace period for late returns (minutes)')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Buffer time between bookings (minutes)')),
                ('late_fee_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Late fee per unit per hour', max_digits=10)),
                ('late_fee_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum late fee', max_digits=10)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_return_time', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('renter_notes', models.TextField(blank=True, help_text='Notes from renter')),
                ('owner_notes', models.TextField(blank=True, help_text='Notes from owner')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='assets.asset')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
            },
        ),
    ]
