# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('contracts', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_contract', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='booking',
            name='dispute',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_dispute', to='payments.dispute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_payment', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookinglock',
            index=models.Index(fields=['resource_type', 'resource_id'], name='booking_loc_resourc_acf55b_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinglock',
            index=models.Index(fields=['expires_at'], name='booking_loc_expires_53ad64_idx'),
        ),
        migrations.AddField(
            model_name='bookingstatustransition',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingtimeline',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='bookings.booking'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['asset', 'start_time', 'end_time'], name='availabilit_asset_i_d4e6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['asset', 'is_available'], name='availabilit_asset_i_f0ddef_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('booked_quantity__lte', models.F('capacity'))), name='booked_not_exceed_capacity'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['renter'], name='bookings_renter__47c407_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['asset'], name='bookings_asset_i_2d48a5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='bookings_start_t_3b5408_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['end_time'], name='bookings_end_tim_d7096b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_time'], name='bookings_status_28164a_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='end_time_after_start_time'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='quantity_at_least_1'),
        ),
    ]
