# Generated by Django 5.2.11 on 2026-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
    ]
