# Generated by Django 5.2.11 on 2026-05-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='late_fee_max',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Maximum late fee', max_digits=10, null=True),
        ),
    ]
