# Generated by Django 5.2.11 on 2026-05-02 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_asset_type'),
        ('bookings', '0004_alter_booking_late_fee_max'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('WEDDING', 'Wedding'), ('CONFERENCE', 'Conference'), ('OTHER', 'Other')], max_length=50)),
                ('event_date', models.DateField()),
                ('duration_hours', models.PositiveIntegerField()),
                ('headcount', models.PositiveIntegerField()),
                ('setup_time_hours', models.PositiveIntegerField(default=2)),
                ('teardown_time_hours', models.PositiveIntegerField(default=1)),
                ('catering_required', models.BooleanField(default=False)),
                ('av_required', models.BooleanField(default=False)),
                ('add_ons', models.JSONField(default=list)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_valid_until', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUOTED', 'Quoted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
            options={
                'verbose_name': 'Venue Quote',
                'verbose_name_plural': 'Venue Quotes',
                'db_table': 'venue_quotes',
            },
        ),
    ]
