# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('BANK_TRANSFER', 'Bank Transfer'), ('ZENOPAY_WALLET', 'Zenopay Wallet')], default='CREDIT_CARD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ESCROW', 'In Escrow'), ('RELEASED', 'Released to Owner'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed'), ('FROZEN', 'Frozen (Dispute)')], default='PENDING', max_length=20)),
                ('zenopay_transaction_id', models.CharField(blank=True, max_length=100)),
                ('zenopay_authorization_code', models.CharField(blank=True, max_length=100)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('escrow_held_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_released_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('refund_reason', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('penalty_reason', models.TextField(blank=True)),
                ('failure_code', models.CharField(blank=True, max_length=50)),
                ('failure_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_info', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('DAMAGE', 'Property Damage'), ('NO_SHOW', 'No Show'), ('LATE_RETURN', 'Late Return'), ('NOT_AS_DESCRIBED', 'Not As Described'), ('CANCELLATION', 'Unauthorized Cancellation'), ('REFUND_NOT_RECEIVED', 'Refund Not Received'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('disputed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('EVIDENCE_COLLECTION', 'Evidence Collection'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('resolution', models.CharField(blank=True, choices=[('REFUND_RENTER', 'Full Refund to Renter'), ('REFUND_PARTIAL', 'Partial Refund to Renter'), ('RELEASE_OWNER', 'Full Release to Owner'), ('RELEASE_PARTIAL', 'Partial Release to Owner'), ('NO_ACTION', 'No Action')], max_length=30)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_info', to='bookings.booking')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_disputes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispute', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'db_table': 'disputes',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['booking'], name='payments_booking_4c4815_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['zenopay_transaction_id'], name='payments_zenopay_62ba26_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_status_811094_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['booking'], name='disputes_booking_2aad4d_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['initiated_by'], name='disputes_initiat_317f73_idx'),
        ),
    ]
