# Generated by Django 5.2.11 on 2026-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('MPESA', 'Vodacom M-Pesa'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('HALOPESA', 'Halo Pesa'), ('AZAM_PESA', 'Azam Pesa'), ('CRDB', 'CRDB Bank'), ('NMB', 'NMB Bank'), ('ABSA', 'Absa Bank'), ('STANBIC', 'Stanbic Bank'), ('NBC', 'NBC Bank'), ('ZENOPAY_WALLET', 'Zenopay Wallet')], default='CREDIT_CARD', max_length=20),
        ),
    ]
