# Generated by Django 5.2.11 on 2026-03-13 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_offlinepaymentmethod_subscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='manual_confirmation',
            field=models.TextField(blank=True, help_text='Transaction ID or confirmation message'),
        ),
        migrations.AddField(
            model_name='payment',
            name='manual_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payment_receipts/bookings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='offline_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_payments', to='payments.offlinepaymentmethod'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ESCROW', 'In Escrow'), ('RELEASED', 'Released to Owner'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed'), ('FROZEN', 'Frozen (Dispute)'), ('PENDING_APPROVAL', 'Pending Approval')], default='PENDING', max_length=20),
        ),
    ]
