# Generated by Django 5.2.11 on 2026-03-13 07:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_manual_confirmation_payment_manual_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlinepaymentmethod',
            options={'ordering': ['display_order', 'network_name']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manual_confirmation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='manual_receipt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='offline_method',
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('LIPA_NAMBA', 'Lipa Namba')], default='MOBILE_MONEY', max_length=20),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code image for Lipa Namba payments', null=True, upload_to='payment_qr/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='qr_instructions',
            field=models.TextField(blank=True, help_text='Instructions for scanning QR code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized'), ('ESCROW', 'In Escrow'), ('RELEASED', 'Released to Owner'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUND', 'Partially Refunded'), ('FAILED', 'Failed'), ('DISPUTED', 'Disputed'), ('FROZEN', 'Frozen (Dispute)')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGO_PESA', 'Tigo Pesa'), ('AIRTEL_MONEY', 'Airtel Money'), ('HALOPESA', 'Halo Pesa'), ('AZAM_PESA', 'Azam Pesa'), ('CRDB', 'CRDB Bank'), ('NMB', 'NMB Bank'), ('OTHER', 'Other')], max_length=20)),
                ('account_name', models.CharField(help_text='Name on the account', max_length=100)),
                ('account_number', models.CharField(help_text='Phone number or account number', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions for payers')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='user_payment_qr/%Y/%m/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('ASSET', 'Asset Booking'), ('RIDE', 'Ride Seat Booking')], max_length=10)),
                ('booking_id', models.UUIDField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100)),
                ('confirmation_message', models.TextField(blank=True, help_text="User's message about the payment")),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='manual_payment_receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin upon approval/rejection')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_payments', to='payments.offlinepaymentmethod')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_manual_payments', to=settings.AUTH_USER_MODEL)),
                ('user_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='payments.userpaymentmethod')),
            ],
            options={
                'db_table': 'manual_payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
