# Generated by Django 5.2.11 on 2026-03-18 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0007_alter_offlinepaymentmethod_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='is_system_wide',
            field=models.BooleanField(default=False, help_text='True for Super Admin, False for Users'),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='lipa_namba',
            field=models.CharField(blank=True, help_text='Lipa Namba for quick payments', max_length=100),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_offline_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinepaymentmethod',
            name='qr_code_image',
            field=models.ImageField(blank=True, help_text='QR Code image for Lipa Namba', null=True, upload_to='payment_qr_images/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='ManualPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('sender_phone_number', models.CharField(max_length=20)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('transaction_message', models.TextField(help_text='For pasting SMS')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manual_payment_receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
