# Generated by Django 5.2.11 on 2026-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_offlinepaymentmethod_is_system_wide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpayment',
            name='booking_type',
            field=models.CharField(choices=[('ASSET', 'Asset Booking'), ('RIDE', 'Ride Seat Booking'), ('SUBSCRIPTION', 'Subscription')], max_length=15),
        ),
        migrations.DeleteModel(
            name='SubscriptionPayment',
        ),
    ]
