# Generated by Django 5.2.11 on 2026-02-22 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_registration_fee', models.DecimalField(decimal_places=2, default=50000.0, help_text='One-time registration fee if subscription is not used', max_digits=12)),
                ('business_subscription_monthly', models.DecimalField(decimal_places=2, default=15000.0, help_text='Monthly subscription price for Business Tier', max_digits=12)),
                ('business_subscription_yearly', models.DecimalField(decimal_places=2, default=150000.0, help_text='Yearly subscription price for Business Tier (Discounted)', max_digits=12)),
                ('business_terms_conditions', models.TextField(default='Standard KIBOSS Business Terms: All assets must be verified. Stamped legal documents required.', help_text='Terms and conditions shown during business registration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
