# Generated by Django 5.2.11 on 2026-02-17 06:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('messaging', '0001_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='context_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='context_type',
            field=models.CharField(blank=True, choices=[('ASSET', 'Asset'), ('BOOKING', 'Booking'), ('RIDE', 'Ride')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['context_type', 'context_id'], name='message_thr_context_b5ead2_idx'),
        ),
    ]
