# Generated by Django 5.2.11 on 2026-02-22 18:22

import kiboss.apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_thread_context_id_thread_context_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageattachment',
            name='file',
            field=models.FileField(upload_to='message_attachments/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_attachment_extension]),
        ),
    ]
