# Generated by Django 5.2.11 on 2026-02-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_tier',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium'), ('gold', 'Gold')], default='none', max_length=20),
        ),
    ]
