# Generated by Django 5.2.11 on 2026-02-22 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_verification_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('verification_documents', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Profile',
                'verbose_name_plural': 'Corporate Profiles',
                'db_table': 'corporate_profiles',
            },
        ),
    ]
