# Generated by Django 5.2.11 on 2026-02-22 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_corporateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_tier',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic'), ('premium', 'Premium'), ('gold', 'Gold'), ('business', 'Business')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='BusinessSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_proof_url', models.URLField(blank=True, help_text='Direct URL to receipt if uploaded manually')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.corporateprofile')),
            ],
            options={
                'db_table': 'business_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
