# Generated by Django 5.2.11 on 2026-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_verification_tier_businesssubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
    ]
