# Generated by Django 5.2.11 on 2026-02-22 18:22

import kiboss.apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_country_alter_userprofile_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_document_extension]),
        ),
    ]
