# Generated by Django 5.2.11 on 2026-02-22 22:58

import django.db.models.deletion
import kiboss.apps.common.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('EMAIL', 'Email Verification'), ('PHONE', 'Phone Verification'), ('IDENTITY', 'Identity Verification'), ('ADDRESS', 'Address Verification'), ('BUSINESS', 'Business Verification')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('document_type', models.CharField(blank=True, help_text='Type of ID document (passport, national_id, drivers_license)', max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_country', models.CharField(blank=True, max_length=100)),
                ('document_front', models.ImageField(blank=True, help_text='Front of ID document', null=True, upload_to='verification/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension])),
                ('document_back', models.ImageField(blank=True, help_text='Back of ID document', null=True, upload_to='verification/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension])),
                ('selfie', models.ImageField(blank=True, help_text='Selfie with ID document', null=True, upload_to='verification/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension])),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('proof_of_address', models.ImageField(blank=True, help_text='Utility bill or bank statement', null=True, upload_to='verification/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension])),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('code_attempts', models.PositiveIntegerField(default=0)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'db_table': 'verification_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='users.verificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'db_table': 'verification_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('document', models.ImageField(upload_to='verification/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='users.verificationrequest')),
            ],
            options={
                'verbose_name': 'Verification Document',
                'verbose_name_plural': 'Verification Documents',
                'db_table': 'verification_documents',
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['user', 'verification_type'], name='verificatio_user_id_8b0213_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['status'], name='verificatio_status_6332b7_idx'),
        ),
    ]
