# Generated by Django 5.2.11 on 2026-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_verificationrequest_verificationlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateprofile',
            name='business_category',
            field=models.CharField(choices=[('RIDE', 'Ride Business'), ('ASSET', 'Asset Business')], default='ASSET', max_length=10),
        ),
    ]
