# Generated by Django 5.2.11 on 2026-02-27 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_corporateprofile_business_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_tier',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('PLUS', 'Plus Tier')], default='FREE', help_text='User subscription tier (Corporate is determined by CorporateProfile)', max_length=20),
        ),
        migrations.CreateModel(
            name='CorporateWorker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Invite email for the worker', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Display name (before user accepts)', max_length=255)),
                ('role', models.CharField(choices=[('DRIVER', 'Driver'), ('ACCOUNTANT', 'Accountant'), ('MANAGER', 'Manager'), ('SUPPORT', 'Customer Support')], max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='INVITED', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corporate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='users.corporateprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_employments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Corporate Worker',
                'verbose_name_plural': 'Corporate Workers',
                'db_table': 'corporate_workers',
                'indexes': [models.Index(fields=['corporate_profile'], name='corporate_w_corpora_c56787_idx'), models.Index(fields=['user'], name='corporate_w_user_id_62d7ab_idx'), models.Index(fields=['role'], name='corporate_w_role_877485_idx')],
                'unique_together': {('corporate_profile', 'email')},
            },
        ),
    ]
