# Generated by Django 5.2.11 on 2026-02-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_account_tier_corporateworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_tier',
            field=models.CharField(choices=[('FREE', 'Free Tier'), ('PLUS', 'Plus Tier'), ('BUSINESS', 'Business Tier')], default='FREE', help_text='User subscription tier (FREE, PLUS, or BUSINESS)', max_length=20),
        ),
    ]
