# Generated by Django 5.2.11 on 2026-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='historical_rides_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='historical_vehicles_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesssubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING_CANCELLATION', 'Pending Cancellation'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('PENDING_CANCELLATION', 'Pending Cancellation'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
