# Generated by Django 5.2.11 on 2026-04-21 23:01

import kiboss.apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_historical_rides_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension]),
        ),
    ]
