# Generated by Django 5.2.11 on 2026-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_userprofile_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateprofile',
            name='business_category',
            field=models.CharField(choices=[('RIDE', 'Ride / Transport Business'), ('HOSPITALITY', 'Hotel / Guest House / Hostel'), ('HOME_SHARING', 'Home Sharing (Airbnb-style)'), ('VENUE', 'Event Venue / Conference Center'), ('STUDIO', 'Studio / Creative Space'), ('COWORKING', 'Co-working / Office Space'), ('EQUIPMENT', 'Equipment / Tool Rental'), ('ENTERTAINMENT', 'Entertainment / Recreation'), ('ENTERPRISE', 'General Enterprise')], default='ENTERPRISE', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporateworker',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'General Manager'), ('ACCOUNTANT', 'Accountant / Finance'), ('DRIVER', 'Driver'), ('DISPATCHER', 'Dispatcher'), ('MECHANIC', 'Vehicle Mechanic'), ('FRONT_DESK', 'Front Desk / Receptionist'), ('HOUSEKEEPER', 'Housekeeper / Cleaning'), ('CONCIERGE', 'Concierge'), ('MAINTENANCE', 'Maintenance Technician'), ('SECURITY', 'Security Officer'), ('CO_HOST', 'Co-Host (Home Sharing)'), ('CHEF', 'Chef / Kitchen Staff'), ('WAITER', 'Waiter / Server'), ('EVENT_COORDINATOR', 'Event Coordinator'), ('AV_TECHNICIAN', 'AV Technician'), ('SETUP_CREW', 'Setup / Teardown Crew'), ('CATERING_STAFF', 'Catering Staff'), ('RECORDING_ENGINEER', 'Recording Engineer'), ('ASSISTANT_ENGINEER', 'Assistant Engineer'), ('COMMUNITY_MANAGER', 'Community Manager'), ('IT_SUPPORT', 'IT Support'), ('TECHNICIAN', 'Equipment Technician'), ('DELIVERY_DRIVER', 'Delivery Driver'), ('CUSTOMER_SUPPORT', 'Customer Support')], max_length=20),
        ),
    ]
