# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('EXECUTED', 'Executed'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived'), ('VOIDED', 'Voided')], default='PENDING', max_length=20)),
                ('snapshot', models.JSONField(default=dict, help_text='Complete contract terms at time of generation')),
                ('jurisdiction', models.CharField(default='US', max_length=100)),
                ('governing_law', models.CharField(blank=True, max_length=255)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('late_return_policy', models.TextField(blank=True)),
                ('damage_policy', models.TextField(blank=True)),
                ('owner_signature', models.JSONField(blank=True, default=dict)),
                ('renter_signature', models.JSONField(blank=True, default=dict)),
                ('owner_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('renter_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_override', models.BooleanField(default=False)),
                ('admin_override_reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_contracts', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract_info', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('changes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Version',
                'verbose_name_plural': 'Contract Versions',
                'db_table': 'contract_versions',
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_status_093df1_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['booking'], name='contracts_booking_728a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['jurisdiction'], name='contracts_jurisdi_d7b116_idx'),
        ),
    ]
