# Generated by Django 5.2.11 on 2026-05-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='jurisdiction',
            field=models.CharField(default='TZ', max_length=100),
        ),
    ]
