# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor_user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_CHANGE', 'Password Change'), ('TOKEN_REFRESH', 'Token Refresh'), ('PERMISSION_GRANTED', 'Permission Granted'), ('PERMISSION_REVOKED', 'Permission Revoked'), ('ROLE_CHANGED', 'Role Changed'), ('DATA_EXPORT', 'Data Export'), ('SENSITIVE_DATA_ACCESS', 'Sensitive Data Access'), ('SETTINGS_CHANGED', 'Settings Changed'), ('USER_BANNED', 'User Banned'), ('USER_UNBANNED', 'User Unbanned'), ('USER_VERIFIED', 'User Verified'), ('ASSET_VERIFIED', 'Asset Verified'), ('ASSET_REJECTED', 'Asset Rejected'), ('BOOKING_OVERRIDE', 'Booking Override'), ('CONTRACT_OVERRIDE', 'Contract Override'), ('PAYMENT_OVERRIDE', 'Payment Override'), ('DISPUTE_RESOLVED', 'Dispute Resolved'), ('RATING_MODERATED', 'Rating Moderated'), ('SYSTEM_ERROR', 'System Error'), ('SECURITY_ALERT', 'Security Alert')], max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField()),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('justification', models.TextField(blank=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('trace_id', models.UUIDField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_logs_actor_i_5bd818_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_logs_resourc_bda8a6_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
    ]
