# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reliability_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('communication_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('cleanliness_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('timeliness_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('overall_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('badges', models.JSONField(blank=True, default=list)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_details',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('RENTER_TO_OWNER', 'Renter to Owner'), ('OWNER_TO_RENTER', 'Owner to Renter'), ('DRIVER_TO_PASSENGER', 'Driver to Passenger'), ('PASSENGER_TO_DRIVER', 'Passenger to Driver')], max_length=30)),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('reliability_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cleanliness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True, max_length=2000)),
                ('private_feedback', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVEALED', 'Mutually Revealed'), ('MODERATION_PENDING', 'Pending Moderation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('APPEALED', 'Appealed')], default='SUBMITTED', max_length=20)),
                ('is_mutually_revealed', models.BooleanField(default=False)),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('moderation_reason', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_reason', models.TextField(blank=True)),
                ('appealed_at', models.DateTimeField(blank=True, null=True)),
                ('appeal_response', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='bookings.booking')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ratings', to=settings.AUTH_USER_MODEL)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='rides.seatbooking')),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('booking', 'reviewer')},
            },
        ),
    ]
