# Generated by Django 5.2.11 on 2026-03-26 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_currency'),
        ('ratings', '0001_initial'),
        ('rides', '0010_ride_creation_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booking', 'reviewer'), ('ride', 'reviewer')},
        ),
    ]
