# Generated by Django 5.2.11 on 2026-05-02 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_late_fee_max'),
        ('ratings', '0002_alter_rating_unique_together'),
        ('rides', '0010_ride_creation_location_lat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trustdetails',
            name='user',
        ),
        migrations.AlterField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='bookings.booking'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('ride__isnull', True)), models.Q(('booking__isnull', True), ('ride__isnull', False)), _connector='OR'), name='rating_exactly_one_source'),
        ),
        migrations.DeleteModel(
            name='TrustDetails',
        ),
    ]
