# Generated by Django 5.2.11 on 2026-05-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_created_at_and_more'),
        ('ratings', '0004_alter_rating_created_at'),
        ('rides', '0014_alter_ride_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_exactly_one_source',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booking', 'reviewer'), ('ride', 'reviewer')},
        ),
        migrations.AddField(
            model_name='rating',
            name='cargo_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='rides.cargobooking'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('booking', 'reviewer'), ('cargo_ride', 'reviewer'), ('ride', 'reviewer')},
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('cargo_ride__isnull', True), ('ride__isnull', True)), models.Q(('booking__isnull', True), ('cargo_ride__isnull', True), ('ride__isnull', False)), models.Q(('booking__isnull', True), ('cargo_ride__isnull', False), ('ride__isnull', True)), _connector='OR'), name='rating_exactly_one_source'),
        ),
    ]
