# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_id', models.UUIDField()),
                ('justification', models.TextField()),
                ('old_value', models.JSONField(blank=True, default=dict)),
                ('new_value', models.JSONField(blank=True, default=dict)),
                ('approved', models.BooleanField(default=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'db_table': 'admin_actions',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'Verifier')], max_length=20)),
                ('permission', models.CharField(choices=[('USER_VIEW', 'View Users'), ('USER_CREATE', 'Create Users'), ('USER_EDIT', 'Edit Users'), ('USER_DELETE', 'Delete Users'), ('USER_BAN', 'Ban Users'), ('USER_VERIFY', 'Verify Users'), ('ASSET_VIEW', 'View Assets'), ('ASSET_CREATE', 'Create Assets'), ('ASSET_EDIT', 'Edit Assets'), ('ASSET_DELETE', 'Delete Assets'), ('ASSET_VERIFY', 'Verify Assets'), ('ASSET_REJECT', 'Reject Assets'), ('BOOKING_VIEW', 'View Bookings'), ('BOOKING_EDIT', 'Edit Bookings'), ('BOOKING_CANCEL', 'Cancel Bookings'), ('BOOKING_OVERRIDE', 'Override Bookings'), ('CONTRACT_VIEW', 'View Contracts'), ('CONTRACT_EDIT', 'Edit Contracts'), ('CONTRACT_OVERRIDE', 'Override Contracts'), ('PAYMENT_VIEW', 'View Payments'), ('PAYMENT_EDIT', 'Edit Payments'), ('PAYMENT_REFUND', 'Refund Payments'), ('PAYMENT_OVERRIDE', 'Override Payments'), ('DISPUTE_VIEW', 'View Disputes'), ('DISPUTE_RESOLVE', 'Resolve Disputes'), ('RATING_VIEW', 'View Ratings'), ('RATING_MODERATE', 'Moderate Ratings'), ('MESSAGE_VIEW', 'View Messages'), ('MESSAGE_MODERATE', 'Moderate Messages'), ('AUDIT_VIEW', 'View Audit Logs'), ('SETTINGS_EDIT', 'Edit Settings'), ('ROLE_MANAGE', 'Manage Roles')], max_length=50)),
            ],
            options={
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'Verifier')], max_length=20)),
                ('scope_type', models.CharField(blank=True, max_length=50)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'unique_together': {('user', 'role', 'scope_type', 'scope_id')},
            },
        ),
    ]
