# Generated by Django 5.2.11 on 2026-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('USER_VIEW', 'View Users'), ('USER_CREATE', 'Create Users'), ('USER_EDIT', 'Edit Users'), ('USER_DELETE', 'Delete Users'), ('USER_BAN', 'Ban Users'), ('USER_VERIFY', 'Verify Users'), ('ASSET_VIEW', 'View Assets'), ('ASSET_CREATE', 'Create Assets'), ('ASSET_EDIT', 'Edit Assets'), ('ASSET_DELETE', 'Delete Assets'), ('ASSET_VERIFY', 'Verify Assets'), ('ASSET_REJECT', 'Reject Assets'), ('BOOKING_VIEW', 'View Bookings'), ('BOOKING_EDIT', 'Edit Bookings'), ('BOOKING_CANCEL', 'Cancel Bookings'), ('BOOKING_OVERRIDE', 'Override Bookings'), ('CONTRACT_VIEW', 'View Contracts'), ('CONTRACT_EDIT', 'Edit Contracts'), ('CONTRACT_OVERRIDE', 'Override Contracts'), ('PAYMENT_VIEW', 'View Payments'), ('PAYMENT_EDIT', 'Edit Payments'), ('PAYMENT_REFUND', 'Refund Payments'), ('PAYMENT_OVERRIDE', 'Override Payments'), ('DISPUTE_VIEW', 'View Disputes'), ('DISPUTE_RESOLVE', 'Resolve Disputes'), ('RATING_VIEW', 'View Ratings'), ('RATING_MODERATE', 'Moderate Ratings'), ('MESSAGE_VIEW', 'View Messages'), ('MESSAGE_MODERATE', 'Moderate Messages'), ('AUDIT_VIEW', 'View Audit Logs'), ('SETTINGS_EDIT', 'Edit Settings'), ('ROLE_MANAGE', 'Manage Roles'), ('SUPPORT_TICKET', 'Handle Support Tickets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'General Verifier'), ('CAR_VERIFIER', 'Car Verifier'), ('BUSINESS_VERIFIER', 'Business Verifier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'General Verifier'), ('CAR_VERIFIER', 'Car Verifier'), ('BUSINESS_VERIFIER', 'Business Verifier')], max_length=20),
        ),
    ]
