# Generated by Django 5.2.11 on 2026-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'General Verifier'), ('CAR_VERIFIER', 'Car Verifier'), ('RIDE_BUSINESS_VERIFIER', 'Ride Business Verifier'), ('ASSET_BUSINESS_VERIFIER', 'Asset Business Verifier')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('OPS', 'Operations'), ('SUPPORT', 'Support'), ('FINANCE', 'Finance'), ('LEGAL', 'Legal'), ('MODERATOR', 'Moderator'), ('VERIFIER', 'General Verifier'), ('CAR_VERIFIER', 'Car Verifier'), ('RIDE_BUSINESS_VERIFIER', 'Ride Business Verifier'), ('ASSET_BUSINESS_VERIFIER', 'Asset Business Verifier')], max_length=30),
        ),
    ]
