# Generated by Django 5.2.11 on 2026-02-28 06:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='entity_type',
            field=models.CharField(choices=[('USER', 'User'), ('OWNER', 'Owner'), ('DRIVER', 'Driver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='like',
            name='entity_type',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('RIDE', 'Ride'), ('OWNER', 'Owner'), ('REVIEW', 'Review')], max_length=20),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('ASSET', 'Asset'), ('RIDE', 'Ride')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookmarks',
                'indexes': [models.Index(fields=['user', 'entity_type'], name='bookmarks_user_id_cb395d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='bookmarks_entity__eb11e7_idx')],
                'unique_together': {('user', 'entity_type', 'entity_id')},
            },
        ),
    ]
