# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contracts', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('OPEN', 'Open for Booking'), ('FULL', 'Full'), ('DEPARTED', 'Departed'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('route_name', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('departure_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_pattern', models.JSONField(blank=True, default=dict)),
                ('total_seats', models.PositiveIntegerField(default=4)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('reserved_seats', models.PositiveIntegerField(default=0)),
                ('confirmed_seats', models.PositiveIntegerField(default=0)),
                ('vehicle_description', models.CharField(blank=True, max_length=255)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=20)),
                ('driver_notes', models.TextField(blank=True)),
                ('cancellation_cutoff_minutes', models.PositiveIntegerField(default=120, help_text='Minutes before departure after which cancellation is not allowed')),
                ('no_show_cutoff_minutes', models.PositiveIntegerField(default=10, help_text='Minutes after departure to mark no-show')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driven_rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='RideSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], max_length=20)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('waypoints', models.JSONField(blank=True, default=list)),
                ('departure_time', models.TimeField()),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60)),
                ('recurrence_days', models.JSONField(default=list, help_text='Days of week: [0,1,2,3,4,5,6] for Mon-Sun')),
                ('total_seats', models.PositiveIntegerField(default=4)),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride Schedule',
                'verbose_name_plural': 'Ride Schedules',
                'db_table': 'ride_schedules',
            },
        ),
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('PICKUP', 'Pickup Point'), ('DROPOFF', 'Drop-off Point'), ('BOTH', 'Both')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('estimated_arrival', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('stop_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Ride Stop',
                'verbose_name_plural': 'Ride Stops',
                'db_table': 'ride_stops',
                'ordering': ['stop_order'],
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved (Pending Payment)'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('BOARDED', 'Boarded'), ('COMPLETED', 'Completed')], default='RESERVED', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('passenger_notes', models.TextField(blank=True)),
                ('luggage_count', models.PositiveIntegerField(default=0)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('marked_no_show_at', models.DateTimeField(blank=True, null=True)),
                ('no_show_penalty_applied', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_booking', to='contracts.contract')),
                ('dropoff_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_bookings', to='rides.ridestop')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_bookings', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_booking', to='payments.payment')),
                ('pickup_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_bookings', to='rides.ridestop')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_bookings', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Seat Booking',
                'verbose_name_plural': 'Seat Bookings',
                'db_table': 'seat_bookings',
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_status_376a74_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver'], name='rides_driver__8fdcf2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['departure_time'], name='rides_departu_80b9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['origin'], name='rides_origin_7d2835_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['destination'], name='rides_destina_2bae43_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['ride'], name='seat_bookin_ride_id_45df76_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['passenger'], name='seat_bookin_passeng_d07884_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['status'], name='seat_bookin_status_c72d03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='seatbooking',
            unique_together={('ride', 'seat_number')},
        ),
    ]
