# Generated by Django 5.2.11 on 2026-02-17 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetpricing_quantity_discounts'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideschedule',
            name='vehicle_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ride_schedules', to='assets.asset'),
        ),
    ]
