# Generated by Django 5.2.11 on 2026-02-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetpricing_quantity_discounts'),
        ('rides', '0002_rideschedule_vehicle_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='assets.asset'),
        ),
    ]
