# Generated by Django 5.2.11 on 2026-02-18 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_alter_ride_vehicle_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RidePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ride_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rides.ride')),
            ],
            options={
                'verbose_name': 'Ride Photo',
                'verbose_name_plural': 'Ride Photos',
                'db_table': 'ride_photos',
                'ordering': ['order'],
            },
        ),
    ]
