# Generated by Django 5.2.11 on 2026-02-22 18:22

import kiboss.apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ridephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridephoto',
            name='image',
            field=models.ImageField(upload_to='ride_photos/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension]),
        ),
    ]
