# Generated by Django 5.2.11 on 2026-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_ridephoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='rideschedule',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='currency',
            field=models.CharField(default='TZS', max_length=3),
        ),
    ]
