# Generated by Django 5.2.11 on 2026-02-24 08:32

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_currency'),
        ('rides', '0006_alter_ride_currency_alter_rideschedule_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='cargo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='cargo_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price per kg or unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='confirmed_cargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='reserved_cargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_cargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cargo capacity in kg or units', max_digits=10),
        ),
        migrations.AddField(
            model_name='rideschedule',
            name='cargo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rideschedule',
            name='cargo_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rideschedule',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride')], default='PERSONAL', max_length=20),
        ),
        migrations.AddField(
            model_name='rideschedule',
            name='total_cargo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.CreateModel(
            name='CargoBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight or units booked', max_digits=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved (Pending Payment)'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='RESERVED', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('cargo_description', models.TextField(blank=True, help_text='Description of items being shipped')),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dropoff_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_dropoff_bookings', to='rides.ridestop')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_booking', to='payments.payment')),
                ('pickup_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_pickup_bookings', to='rides.ridestop')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_bookings', to='rides.ride')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cargo Booking',
                'verbose_name_plural': 'Cargo Bookings',
                'db_table': 'cargo_bookings',
                'indexes': [models.Index(fields=['ride'], name='cargo_booki_ride_id_afe9a7_idx'), models.Index(fields=['sender'], name='cargo_booki_sender__62172a_idx'), models.Index(fields=['status'], name='cargo_booki_status_fcee65_idx')],
            },
        ),
    ]
