# Generated by Django 5.2.11 on 2026-02-27 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_cargo_enabled_ride_cargo_price_and_more'),
        ('users', '0010_user_account_tier_corporateworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Corporate worker assigned as driver for this ride', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rides', to='users.corporateworker'),
        ),
    ]
