# Generated by Django 5.2.11 on 2026-03-18 15:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_ride_assigned_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='allowable_free_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='flat_cargo_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='is_cargo_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='max_vehicle_weight_capacity_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='payment_required_before_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='price_per_excess_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='cargo_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
