# Generated by Django 5.2.11 on 2026-05-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_ride_creation_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='hire_deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_deposit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_itinerary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_min_advance_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_pax_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_price_type',
            field=models.CharField(choices=[('PER_TRIP', 'Per Trip'), ('PER_DAY', 'Per Day'), ('HOURLY', 'Hourly')], default='PER_TRIP', max_length=20),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_purpose',
            field=models.CharField(blank=True, choices=[('WEDDING', 'Wedding'), ('FUNERAL', 'Funeral/Burial'), ('SPORTS', 'Sports/Team Transport'), ('CORPORATE', 'Corporate Event'), ('SCHOOL_TRIP', 'School Trip'), ('PILGRIMAGE', 'Religious/Pilgrimage'), ('GRADUATION', 'Graduation'), ('AIRPORT_TRANSFER', 'Airport Transfer'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='ride',
            name='hire_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
