# Generated by Django 5.2.11 on 2026-05-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_ride_hire_deposit_amount_ride_hire_deposit_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)')], default='PERSONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='rideschedule',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)')], default='PERSONAL', max_length=20),
        ),
    ]
