# Generated by Django 5.2.11 on 2026-05-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_alter_cargobooking_created_at_alter_ride_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ride', 'verbose_name_plural': 'Rides'},
        ),
    ]
