# Generated by Django 5.2.11 on 2026-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_alter_ride_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)'), ('BREAKDOWN', 'Breakdown / Towing Service')], default='PERSONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='rideschedule',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)'), ('BREAKDOWN', 'Breakdown / Towing Service')], default='PERSONAL', max_length=20),
        ),
    ]
