# Generated by Django 5.2.11 on 2026-05-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_alter_ride_ride_type_alter_rideschedule_ride_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)')], default='PERSONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='rideschedule',
            name='ride_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal Ride'), ('BUSINESS', 'Business Ride'), ('SPECIAL_HIRE', 'Special Hire (Charter)')], default='PERSONAL', max_length=20),
        ),
    ]
