# Generated by Django 5.2.11 on 2026-02-21 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('VEHICLE_VERIFICATION', 'Vehicle Verification'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('ASSET_AUDIT', 'Asset Audit'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('SUPPORT_TICKET', 'Support Ticket')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes Requested'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('assigned_role', models.CharField(blank=True, help_text='Role allowed to pick up this task (e.g. VERIFIER)', max_length=50)),
                ('object_id', models.UUIDField()),
                ('reviewer_notes', models.TextField(blank=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Task',
                'verbose_name_plural': 'Staff Tasks',
                'db_table': 'staff_tasks',
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'assigned_role'], name='staff_tasks_status_2ccbff_idx'), models.Index(fields=['assigned_to'], name='staff_tasks_assigne_080d6b_idx'), models.Index(fields=['task_type'], name='staff_tasks_task_ty_f5d2ab_idx'), models.Index(fields=['content_type', 'object_id'], name='staff_tasks_content_f24a5b_idx')],
            },
        ),
    ]
