# Generated by Django 5.2.11 on 2026-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftask',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
