# Generated by Django 5.2.11 on 2026-02-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_stafftask_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='task_type',
            field=models.CharField(choices=[('VEHICLE_VERIFICATION', 'Vehicle Verification'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('CORPORATE_VERIFICATION', 'Corporate Verification'), ('ASSET_AUDIT', 'Asset Audit'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('SUPPORT_TICKET', 'Support Ticket')], max_length=50),
        ),
    ]
