# Generated by Django 5.2.11 on 2026-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_stafftask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='task_type',
            field=models.CharField(choices=[('VEHICLE_VERIFICATION', 'Vehicle Verification'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('CORPORATE_RIDE_VERIFICATION', 'Corporate Ride Verification'), ('CORPORATE_ASSET_VERIFICATION', 'Corporate Asset Verification'), ('ASSET_AUDIT', 'Asset Audit'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('SUPPORT_TICKET', 'Support Ticket')], max_length=50),
        ),
    ]
