# Generated by Django 5.2.11 on 2026-02-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_stafftask_task_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafftask',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Staff Task', 'verbose_name_plural': 'Staff Tasks'},
        ),
        migrations.AlterField(
            model_name='stafftask',
            name='task_type',
            field=models.CharField(choices=[('VEHICLE_VERIFICATION', 'Vehicle Verification'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('CORPORATE_RIDE_VERIFICATION', 'Corporate Ride Verification'), ('CORPORATE_ASSET_VERIFICATION', 'Corporate Asset Verification'), ('ASSET_AUDIT', 'Asset Audit'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('SUPPORT_TICKET', 'Support Ticket'), ('CUSTOM_TASK', 'Custom Task')], max_length=50),
        ),
    ]
