# Generated by Django 5.2.11 on 2026-05-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_stafftask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftask',
            name='task_type',
            field=models.CharField(choices=[('VEHICLE_VERIFICATION', 'Vehicle Verification'), ('IDENTITY_VERIFICATION', 'Identity Verification'), ('CORPORATE_RIDE_VERIFICATION', 'Corporate Ride Verification'), ('CORPORATE_ASSET_VERIFICATION', 'Corporate Asset Verification'), ('ASSET_VERIFICATION', 'Asset Verification'), ('ASSET_AUDIT', 'Asset Audit'), ('PROMOTION_VERIFICATION', 'Promotion Verification'), ('DISPUTE_RESOLUTION', 'Dispute Resolution'), ('SUPPORT_TICKET', 'Support Ticket'), ('SUBSCRIPTION_VERIFICATION', 'Subscription Verification'), ('HOUSEKEEPING', 'Housekeeping'), ('CUSTOM_TASK', 'Custom Task')], max_length=50),
        ),
    ]
