# Generated by Django 6.0.2 on 2026-02-09 04:46

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('ROOM', 'Room/Space'), ('TOOL', 'Tool/Equipment'), ('VEHICLE', 'Vehicle'), ('SEAT_SERVICE', 'Seat Service (Ride-sharing)'), ('TIME_SERVICE', 'Time-based Service')], default='ROOM', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('jurisdiction', models.CharField(default='US', max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=True)),
                ('total_bookings', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='AssetAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('availability_type', models.CharField(choices=[('ALWAYS', 'Always Available'), ('SCHEDULED', 'Scheduled Availability'), ('CUSTOM', 'Custom Rules')], max_length=20)),
                ('buffer_minutes', models.PositiveIntegerField(default=0)),
                ('min_advance_booking_minutes', models.PositiveIntegerField(default=60, help_text='Minimum time before booking can be made')),
                ('max_advance_booking_days', models.PositiveIntegerField(default=90, help_text='Maximum days in advance a booking can be made')),
                ('schedule', models.JSONField(blank=True, default=dict)),
                ('blocked_dates', models.JSONField(blank=True, default=list)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Availability',
                'verbose_name_plural': 'Asset Availability Rules',
                'db_table': 'asset_availability',
            },
        ),
        migrations.CreateModel(
            name='AssetCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity_type', models.CharField(choices=[('GUEST', 'Guest capacity'), ('SEAT', 'Seat capacity'), ('PARKING', 'Parking spots'), ('WORKSTATION', 'Workstations'), ('BED', 'Bed count'), ('UNIT', 'Unit count')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Capacity',
                'verbose_name_plural': 'Asset Capacities',
                'db_table': 'asset_capacity',
            },
        ),
        migrations.CreateModel(
            name='AssetJurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('license_required', models.BooleanField(default=False)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('insurance_required', models.BooleanField(default=False)),
                ('insurance_details', models.TextField(blank=True)),
                ('permits_required', models.JSONField(blank=True, default=list)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_category', models.CharField(blank=True, max_length=50)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdiction_info', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Jurisdiction',
                'verbose_name_plural': 'Asset Jurisdictions',
                'db_table': 'asset_jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='AssetLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asset Like',
                'verbose_name_plural': 'Asset Likes',
                'db_table': 'asset_likes',
            },
        ),
        migrations.CreateModel(
            name='AssetPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='asset_photos/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Photo',
                'verbose_name_plural': 'Asset Photos',
                'db_table': 'asset_photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssetPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Standard Hourly', 'Weekend Rate'", max_length=100)),
                ('unit_type', models.CharField(choices=[('HOUR', 'Per Hour'), ('DAY', 'Per Day'), ('WEEK', 'Per Week'), ('MONTH', 'Per Month'), ('MILE', 'Per Mile'), ('KM', 'Per Kilometer'), ('SEAT', 'Per Seat'), ('FIXED', 'Fixed Price'), ('UNIT', 'Per Unit')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('min_duration_minutes', models.PositiveIntegerField(default=0)),
                ('max_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of days: [0,1,2,3,4,5,6] for Mon-Sun')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Discount rules, surge pricing, etc.')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Pricing',
                'verbose_name_plural': 'Asset Pricing Rules',
                'db_table': 'asset_pricing',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='AssetTimeGranularity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_duration_minutes', models.PositiveIntegerField(default=60)),
                ('max_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('increment_minutes', models.PositiveIntegerField(default=60)),
                ('any_start_time', models.BooleanField(default=True)),
                ('allowed_start_times', models.JSONField(blank=True, default=list, help_text='List of allowed start times in HH:MM format')),
                ('same_day_booking', models.BooleanField(default=True)),
                ('cutoff_hour', models.PositiveIntegerField(default=18, help_text='Hour of day after which same-day booking is not allowed')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_granularities', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Time Granularity',
                'verbose_name_plural': 'Asset Time Granularities',
                'db_table': 'asset_time_granularity',
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asset_t_fc4c39_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner'], name='assets_owner_i_b9eeda_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_active'], name='assets_is_acti_0f03da_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_listed'], name='assets_is_list_d68a42_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['verification_status'], name='assets_verific_084179_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['average_rating'], name='assets_average_5a4270_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['country', 'city'], name='assets_country_daa1c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetlike',
            unique_together={('asset', 'user')},
        ),
    ]
