# Generated by Django 5.2.11 on 2026-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetpricing',
            name='quantity_discounts',
            field=models.JSONField(blank=True, default=list, help_text='Legacy quantity discount rules'),
        ),
    ]
