# Generated by Django 5.2.11 on 2026-02-21 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetpricing_quantity_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('REGISTRATION', 'Vehicle Registration'), ('INSURANCE', 'Insurance Policy'), ('INSPECTION', 'Safety Inspection'), ('OWNERSHIP', 'Proof of Ownership'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='asset_documents/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Document',
                'verbose_name_plural': 'Asset Documents',
                'db_table': 'asset_documents',
            },
        ),
    ]
