# Generated by Django 5.2.11 on 2026-02-22 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_assetdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_corporate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent property for services (e.g., Hotel for a Room)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_services', to='assets.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ROOM', 'Room/Space'), ('TOOL', 'Tool/Equipment'), ('VEHICLE', 'Vehicle'), ('SEAT_SERVICE', 'Seat Service (Ride-sharing)'), ('TIME_SERVICE', 'Time-based Service'), ('HOTEL', 'Hotel Property'), ('RESTAURANT', 'Restaurant Property'), ('HOTEL_ROOM', 'Hotel Room'), ('CONFERENCE_HALL', 'Conference Hall'), ('DINING_TABLE', 'Dining Table')], default='ROOM', max_length=20),
        ),
    ]
