# Generated by Django 5.2.11 on 2026-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_is_corporate_asset_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='jurisdiction',
            field=models.CharField(default='TZ', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='timezone',
            field=models.CharField(default='Africa/Dar_es_Salaam', max_length=50),
        ),
    ]
