# Generated by Django 5.2.11 on 2026-02-22 18:22

import kiboss.apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_alter_asset_country_alter_asset_jurisdiction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='file',
            field=models.FileField(upload_to='asset_documents/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_document_extension]),
        ),
        migrations.AlterField(
            model_name='assetphoto',
            name='image',
            field=models.ImageField(upload_to='asset_photos/%Y/%m/', validators=[kiboss.apps.common.validators.validate_file_size, kiboss.apps.common.validators.validate_image_extension]),
        ),
    ]
