# Generated by Django 5.2.11 on 2026-05-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_assetdocument_file_alter_assetphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ROOM', 'Room/Space'), ('TOOL', 'Tool/Equipment'), ('VEHICLE', 'Vehicle'), ('SEAT_SERVICE', 'Seat Service (Ride-sharing)'), ('TIME_SERVICE', 'Time-based Service'), ('HOTEL', 'Hotel Property'), ('RESTAURANT', 'Restaurant Property'), ('HOTEL_ROOM', 'Hotel Room'), ('CONFERENCE_HALL', 'Conference Hall'), ('DINING_TABLE', 'Dining Table'), ('OFFICE_SPACE', 'Office Space'), ('APARTMENT', 'Apartment'), ('ENTIRE_HOME', 'Entire Home'), ('PRIVATE_ROOM', 'Private Room in Home'), ('SHARED_ROOM', 'Shared Room'), ('GUEST_HOUSE', 'Guest House'), ('EVENT_VENUE', 'Event Venue'), ('OUTDOOR_SPACE', 'Outdoor Space'), ('BANQUET_HALL', 'Banquet Hall'), ('ROOFTOP', 'Rooftop / Terrace'), ('RECORDING_STUDIO', 'Recording Studio'), ('PHOTO_STUDIO', 'Photography Studio'), ('DANCE_STUDIO', 'Dance / Fitness Studio'), ('PODCAST_STUDIO', 'Podcast Studio'), ('ART_STUDIO', 'Art Studio'), ('HOT_DESK', 'Hot Desk'), ('MEETING_ROOM', 'Meeting Room'), ('PRIVATE_DINING_ROOM', 'Private Dining Room'), ('PARKING_SPACE', 'Parking Space'), ('STORAGE_UNIT', 'Storage Unit'), ('BOAT', 'Boat / Watercraft'), ('BICYCLE', 'Bicycle / E-bike'), ('SPORTS_EQUIPMENT', 'Sports Equipment'), ('GENERATOR', 'Generator'), ('MUSICAL_INSTRUMENT', 'Musical Instrument'), ('CAMERA_EQUIPMENT', 'Camera Equipment')], default='ROOM', max_length=20),
        ),
    ]
