# Generated by Django 5.2.11 on 2026-05-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='instant_book',
            field=models.BooleanField(default=True, help_text='If False, owner must approve before payment'),
        ),
    ]
