# Generated by Django 5.2.11 on 2026-05-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_instant_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('position_in_results', models.PositiveIntegerField()),
                ('was_clicked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_impressions', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewer_ip_hash', models.CharField(max_length=64)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'viewed_at'], name='assets_page_asset_i_a5f43e_idx')],
            },
        ),
    ]
