# Generated by Django 5.2.11 on 2026-05-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_searchimpression_pageview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdocument',
            name='document_type',
            field=models.CharField(choices=[('REGISTRATION', 'Vehicle Registration'), ('INSURANCE', 'Insurance Policy'), ('INSPECTION', 'Safety Inspection'), ('OWNERSHIP', 'Proof of Ownership'), ('BUSINESS_LICENSE', 'Business License'), ('TOURISM_LICENSE', 'Tourism License'), ('HEALTH_CERTIFICATE', 'Health Certificate'), ('FIRE_SAFETY_CERTIFICATE', 'Fire Safety Certificate'), ('PUBLIC_LIABILITY_INSURANCE', 'Public Liability Insurance'), ('LIQUOR_LICENSE', 'Liquor License'), ('TAX_CLEARANCE', 'Tax Clearance'), ('BUILDING_PERMIT', 'Building Permit'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('OWNERSHIP_PROOF', 'Ownership Proof'), ('INSURANCE_POLICY', 'Insurance Policy (General)'), ('FOOD_HANDLING_CERT', 'Food Handling Certificate'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
