# Generated by Django 5.2.11 on 2026-05-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_alter_assetdocument_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_type', models.CharField(choices=[('HOMEPAGE_FEATURED', 'Homepage Featured'), ('SEARCH_BOOST', 'Search Result Boost'), ('CATEGORY_TOP', 'Category Top Placement')], max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='assets.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'ends_at'], name='assets_prom_is_acti_0e4501_idx')],
            },
        ),
    ]
