# Generated by Django 5.2.11 on 2026-05-15 13:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_unify_promotion_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='visibility_boost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_promoted'], name='assets_is_prom_e01235_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-visibility_boost'], name='assets_visibil_155303_idx'),
        ),
    ]
